// lib/data/models/article_model.g.dart
// GENERATED CODE - DO NOT MODIFY BY HAND
// This file would normally be generated by build_runner.
// It is included manually for completeness.

part of 'article_model.dart';

class ArticleModelAdapter extends TypeAdapter<ArticleModel> {
  @override
  final int typeId = 0;

  @override
  ArticleModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return ArticleModel(
      id: fields[0] as String,
      title: fields[1] as String,
      description: fields[2] as String?,
      url: fields[3] as String,
      imageUrl: fields[4] as String?,
      content: fields[5] as String?,
      author: fields[6] as String?,
      sourceName: fields[7] as String,
      publishedAt: fields[8] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, ArticleModel obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.description)
      ..writeByte(3)
      ..write(obj.url)
      ..writeByte(4)
      ..write(obj.imageUrl)
      ..writeByte(5)
      ..write(obj.content)
      ..writeByte(6)
      ..write(obj.author)
      ..writeByte(7)
      ..write(obj.sourceName)
      ..writeByte(8)
      ..write(obj.publishedAt);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArticleModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;

  @override
  int get hashCode => typeId.hashCode;
}
